import smtplib as s

ob = s.SMTP('smtp.gmail.com', 587)
ob.ehlo()
ob.starttls()
ob.login("rokydutta2003@gmail.com", "******")
subject = "Automated mail generated by python program"
body = "Python"
message = "Subject: {}\n\n{}".format(subject, body)
lstaddr=["sukhendudutta2003@gmail.com","sukhendu2022@gift.edu.in"]
ob.sendmail('rokydutta2003@gmail.com',lstaddr,message)
print("Mail sent")
ob.quit()